---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: Basic Auth Example
  description: abc
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: graph.facebook.com
basePath: /v2.4
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  key:
    type: apiKey
    in: query
    name: access_token

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /me:
    get:
      security:
        - key: []
      responses:
        200:
          description: The user object
          schema:
            type: object
