---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "2.4"
  title: Basic Auth Example
  description: abc
    
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: graph.facebook.com
basePath: /v2.4
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  key:
    type: apiKey
    in: query
    name: access_token
security:
  - key: []
################################################################################
#                                   Paths                                      #
################################################################################
  
paths:
  /:
    get:
      security:
       - basicAuth: []
      responses:
        200:
          description:  Will send `Authenticated` if authentication is succesful, otherwise it will send `Unauthorized`
